# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

osx_image: xcode7.2

env:
    matrix:
        - IOS_VERSION=9.2
        - IOS_VERSION=8.4

script:
    - export DEVICE_ID=$(instruments -s devices | grep "iPhone 5s (${IOS_VERSION}" | awk -F '[\[]' '{print $2}' | sed 's/\([-0-9A-F]*\).*/\1/')
    - echo "Using device ${DEVICE_ID}"
    - xargs open -a "simulator" --args -CurrentDeviceUDID $DEVICE_ID
    - set -o pipefail && xcodebuild test -project Louis.xcodeproj -scheme Louis -sdk iphonesimulator -destination "id=${DEVICE_ID}" ONLY_ACTIVE_ARCH=NO | xcpretty
    - pod lib lint
    - bash <(curl -s https://codecov.io/bash)
